spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
  enabled: true
application.config.queue:
  capacity: 50
  dlq-capacity: 500
  max-retries: 3
  ttl-seconds: 300